"""Shared markdown formatter for PR/MR comments.

The shape is intentionally compact so the comment stays useful at a
glance — a header line, severity counts, top-N table of new findings
(or all findings if it's a fresh scan, not a diff).
"""

from __future__ import annotations

from collections import Counter

from aibom.diff import FindingDiff
from aibom.models import ScanResult


_SEV_EMOJI = {
    "critical": "🚨",
    "high":     "⚠️",
    "medium":   "🟡",
    "low":      "🔵",
    "info":     "💬",
}
_SEV_ORDER = ["critical", "high", "medium", "low", "info"]


def format_aibom_comment(result: ScanResult, *, title: str = "AiBOM scan") -> str:
    counts = Counter(f.severity for f in result.findings)
    lines = [
        f"### {title}",
        "",
        _summary_line(counts, len(result.findings)),
        "",
    ]
    high = [f for f in result.findings if f.severity in {"critical", "high"}][:20]
    if high:
        lines.append("| Sev | Rule | File | Summary |")
        lines.append("|---|---|---|---|")
        for f in high:
            lines.append(
                f"| {_SEV_EMOJI.get(f.severity, '')} **{f.severity}** "
                f"| `{f.rule_id}` "
                f"| `{f.path}` "
                f"| {_truncate(f.summary, 120)} |"
            )
    else:
        lines.append("_No critical or high findings._")
    lines.append("")
    lines.append("_Generated by [aibom](https://github.com/HTS-ASPM/aibom)_")
    return "\n".join(lines)


def format_diff_comment(diff: FindingDiff, *, title: str = "AiBOM diff") -> str:
    summary = diff.to_dict()["summary"]
    lines = [
        f"### {title}",
        "",
        (
            f"➕ **{summary['added']} added** · "
            f"➖ **{summary['removed']} removed** · "
            f"⬆️ **{summary['severity_raised']} raised** · "
            f"⬇️ **{summary['severity_lowered']} lowered** · "
            f"= **{summary['unchanged']} unchanged**"
        ),
        "",
    ]
    if diff.added:
        lines.append("#### New findings")
        lines.append("| Sev | Rule | File | Summary |")
        lines.append("|---|---|---|---|")
        for f in sorted(diff.added, key=_severity_rank, reverse=True)[:15]:
            lines.append(
                f"| {_SEV_EMOJI.get(f.severity, '')} **{f.severity}** "
                f"| `{f.rule_id}` "
                f"| `{f.path}` "
                f"| {_truncate(f.summary, 120)} |"
            )
        if len(diff.added) > 15:
            lines.append("")
            lines.append(f"_…and {len(diff.added) - 15} more_")
        lines.append("")
    if diff.severity_raised:
        lines.append("#### Severity raised")
        lines.append("| Rule | File | Before → After |")
        lines.append("|---|---|---|")
        for older, newer in diff.severity_raised[:10]:
            lines.append(
                f"| `{newer.rule_id}` | `{newer.path}` "
                f"| {older.severity} → **{newer.severity}** |"
            )
        lines.append("")
    if not diff.added and not diff.severity_raised:
        lines.append("_No new or raised findings._")
        lines.append("")
    lines.append("_Generated by [aibom](https://github.com/HTS-ASPM/aibom)_")
    return "\n".join(lines)


def _summary_line(counts: Counter, total: int) -> str:
    parts = [f"**{total} findings**"]
    for sev in _SEV_ORDER:
        n = counts.get(sev, 0)
        if n:
            parts.append(f"{_SEV_EMOJI.get(sev, '')} {sev}: **{n}**")
    return " · ".join(parts)


def _truncate(text: str, n: int) -> str:
    text = text.replace("|", "\\|").replace("\n", " ")
    return text if len(text) <= n else text[: n - 1] + "…"


_SEV_RANK = {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}


def _severity_rank(finding) -> int:
    return _SEV_RANK.get(finding.severity, 0)
